import type { Metadata } from "next";
import { Saira, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/Component/Common/Nav";
import Footer from "@/Component/Common/Footer";

const sairaSans = Saira({
  variable: "--font-saira-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sairaSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
